### ISSUE TITLE
Not correct result when using toLocalLowerCase with empty string on android

### ISSUE THREAD

**Issue by DedKerun** [facebook/hermes#582] opened 2021-08-26 15:18 UTC
## Environment

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.8.1
React Native version (if any): 65.1
OS version (if any): MacOS 11.4
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): Android 8, 11

## Steps To Reproduce

1. use "".toLocaleLowerCase()
2. return "뤇熑뽉:love_hotel:뤫퀁쩈ꖆ
㑈쳏䞵뽓짠ꖆ샰띕㑈쳏쩈ꖆ샰띕䟌뽿쨈ꖆᬂ뽙쩈ꖆ샰띕困뤇因뤇囀뤇囀뤇䟌뽿쩸ꖆͣ뽉쩈ꖆ샰띕困뤇因뤇셤띕탨困뤇因뤇셤"

**Comment by mganandraj** [comment] 2021-08-30 14:37
Hi @DedKerun .. Thanks for reporting this issue .. 

What is the default language/locale in your device? The easiest method to get it is to run `adb shell getprop | grep locale` from a shell.

**Comment by DedKerun** [comment] 2021-08-30 14:42
Hi @mganandraj 

[persist.sys.locale]: [ru-RU]
[ro.product.locale]: [en-US]

**Comment by cc-matthias-m** [comment] 2021-09-24 10:04
Hi,

With my team, we get the same error on android with a call of `toLocalLowerCase` on empty string.

Our default language/locale  are
```
[persist.sys.locale]: [fr-FR]
[ro.product.locale]: [en-US]
```

We have the error message `String length exceeds limit, js engine: hermes`.

If we put a `console.log` before the call of `toLocalLowerCase`, we don't get the error message below and the string return is `"뫐冑떡"` .


We are on react-native 0.65.1

**Comment by ptcc** [comment] 2021-11-02 16:35
this seems to only be an issue with some older api levels (happens on 22 but not on 29)

**Comment by neildhar** [comment] 2021-12-06 16:10
This should now be fixed. The symptoms of the bug were fixed in ce59ce1003a2d7f43bd410cd3ae489f034a5eeb0 and the root cause was fixed in 54c878838c5776eb0ce7ab2d0b06804d5141218c.

**Closed by neildhar** 2021-12-06 16:10 UTC
Labels: bug
