### ISSUE TITLE
Hermes should throws a SyntaxError when return is outside function

### ISSUE THREAD

**Issue by igor-simoes** [facebook/hermes#250] opened 2020-05-22 03:29 UTC
Hi everyone,
I found an issue in Hermes that violates the specification [18.2.1.1.1](https://www.ecma-international.org/ecma-262/#sec-performeval-rules-outside-functions) that should throws a SyntaxError (early error) when the `return` is outside function.

version: 0.5.0
OS: Linux Mint 19.2 x64

steps to reproduce:
```
return;
```
Actual results:
error: 'return' not in a function

Expected results:
SyntaxError: 'return' not in a function

V8, SpiderMonkey, JavaScriptCore and Chakra works as expected.

cinfuzz

**Comment by tmikov** [comment] 2020-05-25 16:43
Hi, I am probably missing something, but I don't understand what the problem is. Are you concerned with the text of the error message?

Hermes is producing an early error, as it should.
AFAICT, it also works correctly in eval:
```
try {
    eval("return");
} catch (e) {
    print("eval error", e);
}
```

There are indeed some cases where Hermes deviates slightly from the latter of the spec, by generating an early SyntaxError instead of throwing an exception at runtime, but this doesn't seem to be one of them.

Closing for for now, but please feel free to reopen with more information.

**Closed by tmikov** 2020-05-25 16:43 UTC

**Comment by igor-simoes** [comment] 2020-05-26 13:04
Hi Tzvetan, thanks for response. I thought it should explicitly throw the syntax error, but with eval it works as expected.
