### ISSUE TITLE
Performance characteristics & Optimization strategies

### ISSUE THREAD

**Issue by schmod** [facebook/hermes#907] opened 2023-01-31 15:47 UTC
## Description

I recently opened [an issue](https://github.com/facebook/react-native-website/issues/3532) in the `react-native-website` repository, about the fact that many of the officially-documented React-Native [performance optimization tips](https://reactnative.dev/docs/ram-bundles-inline-requires) appear to be specific to JSC, and are either unnecessary or harmful when applied to apps that target Hermes.

Given that Hermes is now the default engine for React-Native, this page is somewhat archaic, and needs to be updated to reflect any performance-optimization advice that developers should heed when developing for Hermes.  

The R-N folks suggested that I bring this discussion up directly here.  

Hermes is a somewhat unusual JavaScript engine, and has somewhat unusual performance characteristics, especially from the perspective of the typical JS developer, who is accustomed to optimizing applications for V8, SpiderMonkey, JSC, or Chakra.  While much has been written about how Hermes **_is_** different, I've seen little documentation about **_how_** developers should understand and capitalize upon these differences.  

A few specific questions spring to mind: 
* RAM bundles are unsupported in Hermes.  Will this be a future feature, or does Hermes obviate the need for this optimization?  If so, why?  
* Is there any benefit to using inline requires with Hermes?  (Again: If not, why?)
* What should developers do if they are observing slow cold-boot times in their Hermes-based React-Native app?
* Are there any language features or workloads that have _substantially_ different performance characteristics in Hermes, compared to a traditional JS engine?  

The answer very well may be that Hermes handles all of this for us!  If that's the case, we simply need to update or remove the existing documentation to make that clear.

**Comment by tmikov** [comment] 2023-01-31 22:17
Hi, this is a very interesting and important topic. Thank you for bringing it up. I have tried to answer some of your questions below:

> RAM bundles are unsupported in Hermes. Will this be a future feature, or does Hermes obviate the need for this optimization? If so, why?

RAM bundles are not a feature of the JS engine, so technically there is nothing preventing the implementation of RAM bundles for Hermes (preferably using bytecode instead of source, but same principle). But it would be a regression, since the bytecode format used by Hermes already provides all the benefits of RAM bundles and more. 

The goal of RAM bundles is to delay parsing and loading of a module until it is actually required. In Hermes obviously there is no parsing, since everything is already compiled to bytecode, so parsing is not an issue. 

What about loading?  Hermes bytecode is [memory mapped](https://man7.org/linux/man-pages/man2/mmap.2.html) into RAM, which means that pages are automatically loaded by the OS only when executed for the first time. Further improvements can be made by reordering functions globally, though there hasn't been too much interest in that.

So, Hermes applications already automatically get all the benefits of RAM bundles and more.

> Is there any benefit to using inline requires with Hermes? 

Yes. Inline requires delay the execution of module initialization.  If that initialization is expensive, it may be beneficial to postpone it until it is needed.

By the way, Hermes has a built-in implementation of CommonJS, which is more efficient than the one provided by the bundler, making inline requires cheaper. Unfortunately, as far as I know, nobody is using it yet.
 
> What should developers do if they are observing slow cold-boot times in their Hermes-based React-Native app?

In our experience, the most frequent reason for slower boot of a Hermes app is if the developer accidentally packaged the app with JS source, instead of bytecode. A second reason might be if they are using a debug version of Hermes.

Other than those reasons, it is very unlikely that a Hermes based app would boot slower than JSC.

> Are there any language features or workloads that have substantially different performance characteristics in Hermes, compared to a traditional JS engine?

Heavy computational tasks (crypto, 3d math, etc) are currently significantly slower in an interpreter like Hermes compared to a JIT.

**Comment by zzz08900** [comment] 2023-02-03 04:36
>Heavy computational tasks (crypto, 3d math, etc) are currently significantly slower in an interpreter like Hermes compared to a JIT.

Does that mean, if I have a computational heavy re-render happening and I'm using Hermes with RN, the app will experience more frame drop compared to using JSC?

But I guess I should be tweaking the re-render process, not the JS engine under that situation, right?

**Comment by tmikov** [comment] 2023-02-03 16:53
@zzz08900 it depends on what you mean by computationally heavy. If your render is performing tens of thousands of computations in tight loops, a JIT like JSC will probably perform better in that case.

BTW, we are working on improving Hermes performance for those cases, but as it currently is, a JIT will be faster.

**Comment by radex** [comment] 2023-02-20 15:21
> JIT like JSC will probably perform better in that case

JSC in RN (i.e. outside of Safari) does not use JIT compilation

**Comment by neildhar** [comment] 2023-02-20 17:05
> JSC in RN (i.e. outside of Safari) does not use JIT compilation

My recollection is that while JSC in RN cannot JIT on iOS, the baseline JIT is enabled on Android.

**Comment by tmikov** [comment] 2023-05-17 00:01
Closing the issue, since there seem to be no more questions.

**Closed by tmikov** 2023-05-17 00:01 UTC
