### ISSUE TITLE
Potential performance improvement. 

### ISSUE THREAD

**Issue by Szymon20000** [facebook/hermes#1572] opened 2024-11-27 13:51 UTC
## Problem
I'm profiling a RN app and noticed huge performance problems with calling js function from jsi level. I digged  into it and it turned out that most of the time is spend on pthread_getattr_np (on android).  Here is a screenshot from android studio sampling profiler <img width="493" alt="Screenshot 2024-11-27 at 14 48 53" src="https://github.com/user-attachments/assets/414c8988-70d9-432c-b548-1e1124449f16">

## Solution
Would it be possible to just cache it? Chat GPT suggests something like this:
```
std::pair<const void *, size_t> thread_stack_bounds(unsigned gap) {
    static thread_local std::pair<const void *, size_t> cachedBounds;
    static thread_local bool isCached = false;

    if (!isCached) {
        pthread_attr_t attr;
        pthread_attr_init(&attr);

        if (pthread_getattr_np(pthread_self(), &attr) != 0) {
            hermes_fatal("Unable to obtain native stack bounds");
        }

        void *origin;
        size_t size;
        if (pthread_attr_getstack(&attr, &origin, &size) != 0) {
            pthread_attr_destroy(&attr);
            hermes_fatal("Unable to obtain stack attributes");
        }

#ifdef __BIONIC__
        // Adjust for guard pages on Android/Bionic
        size_t guardSize;
        if (pthread_attr_getguardsize(&attr, &guardSize) != 0) {
            guardSize = 0; // Default to 0 on error
        }
        if (guardSize > size) {
            guardSize = size;
        }
        origin = static_cast<char *>(origin) + guardSize;
        size -= guardSize;
#endif

        pthread_attr_destroy(&attr);

        // Cache the result
        cachedBounds = {static_cast<char *>(origin) + size, size};
        isCached = true;
    }

    // Adjust for the requested gap
    const auto &[stackEnd, stackSize] = cachedBounds;
    size_t adjustedSize = gap < stackSize ? stackSize - gap : 0;
    return {stackEnd, adjustedSize};
}
```

**Comment by Szymon20000** [comment] 2024-11-27 15:45
<img width="700" alt="Screenshot 2024-11-27 at 16 45 04" src="https://github.com/user-attachments/assets/d934a6ce-b8d2-48dd-8934-daf90acd7aaf">
I see it's called multiple times and I check main thread only (used by reanimated).

**Comment by Szymon20000** [comment] 2024-11-27 15:47
<img width="531" alt="Screenshot 2024-11-27 at 16 46 29" src="https://github.com/user-attachments/assets/1841d59f-80a9-4d53-a50b-8f74f526a9e5">

**Comment by tmikov** [comment] 2024-11-27 16:02
Sorry, I don't understand what  these screenshots are supposed to tell me.

**Comment by Szymon20000** [comment] 2024-11-27 16:08
That is flame graph from a single thread. On those screenshots you can see that thread_stack_bounds is called multiple times. If it would be cached in this flow we would see it only once. workouts::SharebleWorklet::toJSValue calls another jsi::Function which calls ScopedNativeCallFrame which finally calls thread_stack_bounds. There are 2 such calls on the first screenshot and 3 on the second one. The last screenshot is just to show that all comes from the same thread :).

**Comment by tmikov** [comment] 2024-11-27 17:11
I am not opposed to adding per-thread caching, but before we do it, I would like to understand the use case.

So, is the case that we are getting calls to the same runtime from the same two  threads, just switching between them?

Also, when this happens, is the JS stack empty?

**Comment by Szymon20000** [comment] 2024-11-27 17:21
Ah so currently Hermes only keeps last thread cached? The calls I showed are only from main but it is possible that between them the runtime is accessed from other threads.

**Comment by Szymon20000** [comment] 2024-11-27 17:26
If that's the case then it looks like a bug in Reanimated (@bartlomiejbloniarz maybe synchronous calls blocks UI thread but access runtime from js-thread?) but at the same time the same thing can happen in fabric when we (sometimes) render synchronously on UI thread but I would need to check if that happens actually on Js thread and we just block the UI or it happens on UI actually.

**Comment by Szymon20000** [comment] 2024-11-27 17:41
@bartlomiejbloniarz I think it's enough to block js thread and schedule a call on UI this will probably fix this problem. Right now it takes lock and uses runtime on JS thread. https://github.com/software-mansion/react-native-reanimated/blob/0162804a8ace2a8f6b77764894d8e4d87f94781a/packages/react-native-reanimated/Common/cpp/worklets/WorkletRuntime/WorkletRuntime.cpp#L84

**Comment by Szymon20000** [comment] 2024-11-27 18:32
https://github.com/software-mansion/react-native-reanimated/pull/6770 @bartlomiejbloniarz This seems to fix it but at the same time now we need to wait for the main thread even when reanimated is currently not using the thread. So I think caching per thread would be actually better @tmikov . 

Another approach would be to make reanimated use separate thread and also call runSync from UI but not sure how bit would be the overhead.

**Comment by bartlomiejbloniarz** [comment] 2024-11-28 10:30
@tmikov yes. We've seen this in one of our client's apps, that they had many calls to our hermes runtime from both UI and the JS thread simultaneously. They weren't able to give me a reproduction, but I was able to reproduce it "artificially," simply by:
- running a reanimated animation (on the UI thread)
- reading from a shared value from a setInterval (this triggers synchronous calls to our runtime from the JS thread)
I think a more natural scenario for this to happen would be if someone was running an animation on a component with an `onLayout` callback, that was doing reads from a reanimated shared value. 

I think that usually it's an anti-pattern to do this in reanimated (but there might be some cases when it is necessary, I just haven't seen them yet). Adding per-thread caching would be I think the best solution for us.

**Comment by Szymon20000** [comment] 2024-11-28 11:26
![Screenshot 2024-11-28 at 12 26 32](https://github.com/user-attachments/assets/859901c9-6ab5-4bfc-8676-c3938f26efda)

**Comment by tjzel** [comment] 2024-11-28 13:16
@tmikov 
To simplify the use case a bit better:

In Reanimated we don't exactly couple additional runtimes to a given thread. They're considered resources which any thread could potentially obtain for a period of time.

Sometimes, a runtime (let's call it Primary) might require synchronization of some data with another runtime (Secondary) on a user's request. *Whether this request is reasonable from the user's App design perspective is a whole another topic.* Because the runtimes aren't coupled to a thread, it might occur that Secondary isn't used by any thread at the moment and we can acquire it "freely" from Primary's thread. In result we get a much faster sync. Secondary is released by the Primary's thread after the sync and we are back where we were.

At the time we preferred that solution to it's alternative - runtime-thread coupling.

In the coupling scenario, we'd need to schedule an operation from the Primary's thread to the Secondary's thread. This seems good on paper - except for the fact that in the majority of our cases the Secondary's thread is the Main thread. Schedule the operation at an unlucky moment and you might need to wait for a very long time to get its result.

@bartlomiejbloniarz Please correct me if I omitted/oversimplified some things here.

**Comment by gaearon** [comment] 2024-12-05 16:41
@tmikov Do you have enough information from the responses above or is there still uncertainty about the use cases? Just trying to figure out where it is & if there's something actionable to do to move this forward. Thanks!

**Comment by tmikov** [comment] 2024-12-05 20:10
We are adding this optimization.

**Comment by tmikov** [comment] 2024-12-06 21:43
The fix landed in Static Hermes here: https://github.com/facebook/hermes/commit/4fc57f35c8aefc152120da0cc31f00eb5dddbf1c

We are backporting it to Hermes as well.

**Comment by tmikov** [comment] 2024-12-09 21:10
Backport landed in Hermes https://github.com/facebook/hermes/commit/568b1c99be3560e9634d04c1213813049dcfce6f.

**Closed by tmikov** 2024-12-09 21:10 UTC
Labels: enhancement

**Comment by hansihe** [comment] 2025-03-26 19:45
I dug into a related issue, and thought I would share what I found as root cause.

Looking at the source code [`pthread_getattr_np` in `bionic`](https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/bionic/pthread_attr.cpp#198) (androids libc), we see that there is a conditional call to `__pthread_attr_getstack_main_thread` when called from the main thread only. This ends up in [`__find_main_stack_limits`](https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/bionic/pthread_internal.cpp#159), which reads from `/proc/self/maps` and parses the contents to find the stack.

This means that when called from the main thread on android specifically, `pthread_getattr_np` reads a file and parses the text contents.

**Comment by edkimmel** [comment] 2025-04-11 16:18
Are there any plans to back port this further to RN 0.76 / 0.77?

**Comment by tmikov** [comment] 2025-04-11 18:25
We (the Hermes team) don't manage RN backports and point releases. But if this ports cleanly to earlier versions, you can request a pick in RN.

**Comment by Gopinatha-L** [comment] 2025-04-14 05:43
> Are there any plans to back port this further to RN 0.76 / 0.77?

+1
