### ISSUE TITLE
Error messages should be reported according to the human-machine index, depending on their debug level.

### ISSUE THREAD

**Issue by meftunca** [facebook/hermes#738] opened 2022-04-28 14:23 UTC
Error messages should be reported according to the human-machine index, depending on their debug level. I need to go back to jsc to find some errors. Because I get unhelpful errors like 'undefined function is not a function'.

As a workaround, the debug level can be adjusted according to the production and development environment. This way you can scale the error messages.

**Comment by tmikov** [comment] 2022-04-28 15:36
@meftunca I just ran the following code:
```
var x;
if (true)
    x();
```

and got the following error:
```
Uncaught TypeError: undefined is not a function
    at global (t.js:3:6)
```

It explicitly tells you where the error occurred: in t.js, line 3, column 6. If you open the file in an editor and go to that location you can see the function call `x()`. What is unclear about that error?

**Comment by meftunca** [comment] 2022-04-28 17:10
Thank you for the quick turnaround. This is an optimistic scenario. Unfortunately, I don't get such a clean error return for indirect errors that depend on libraries.

React native was also showing the error in my code block on react-native-safearea-context. I was able to solve the problem by switching to jsc and getting a clearer error message. And this process has been really painful.

**Comment by tmikov** [comment] 2022-04-28 22:12
@meftunca I am sorry, but I still don't understand what the problem is. You are saying that you were unhappy with an error message under some unclear circumstances, but you are not providing any information about it. What was the exact error that you got and why was it unsatisfactory? What should it have looked like?

**Comment by jpporto** [comment] 2022-12-19 22:28
Hi,

We have just landed a [feature](https://github.com/facebook/hermes/commit/2f73e847983910f3c69e5496ab12573b1293d681) that allows Hermes to issue more human-friendly error messages. In order to use the feature, you need to compile your JS bundle with debug information (otherwise you'll get the previous behavior).

John Paul

**Comment by jpporto** [comment] 2023-02-06 20:59
Hi,

as of [this commit](https://github.com/facebook/hermes/commit/2f73e847983910f3c69e5496ab12573b1293d681) hermes can and will emit more human-friend errors. Make sure you are past that diff, and that you compile your bundle with debug info.

John Paul

**Closed** 2023-02-09 12:51 UTC
