### ISSUE TITLE
Can't use NativeDriver for animation with Hermes Engine

### ISSUE THREAD

**Issue by mananbordia** [facebook/hermes#918] opened 2023-02-17 19:11 UTC
## Bug Description
I am trying to migrate my app to latest `expo sdk : 47.0.13` (`react-native: 0.70.5`) with jsEngine: 'hermes for android.
My app contains `useNativeDriver:true` for animation config and because of that it is crashes with error : 
```
RangeError: Property storage exceeds 196607 properties
``` 
For animation I am using Animated (Animated.timing) from react-native.
I have checked that this issue is not an issue when `jsc` is used as jsEngine instead of hermes.
I have run reinstalled the app using `expo run:android` and got the same error.
Although i am facing this issue on expo I believe this is related to Hermes engine or (and) Animated by react native.

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version:
React Native version (if any):0.70.5
OS version (if any):Android 12
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): arm64-v8a

## Steps To Reproduce

Here is the github repo for complete code : https://github.com/mananbordia/Minimal-Repro-Code-Hermes-useNativeDriver

Here is the related snippet of code : `App.js`

```
import {Animated} from 'react-native';
import {useRef, useEffect, useState} from 'react';

const TIMECONST = 20000000; // Replace this with 2000000 to see the animation even with native driver
const CountDown = () => {
  const [timeLeft,_] = useState(TIMECONST);
  const [totalDuration, __] = useState(2 * TIMECONST);
  const progressRef = useRef(new Animated.Value(Math.min(timeLeft / totalDuration, 1))).current;

  useEffect(() => {
    console.log('Animation started...');
    Animated.timing(progressRef, {
      toValue: 0,
      duration: timeLeft,
      useNativeDriver: true, // Set this to true and it will work with hermes engine
    }).start(() => {
      console.log('Callback function for animation');
    });

    return () => progressRef.stopAnimation();
  }, []);

  const width = 200;
  const animatedScale = progressRef.interpolate({
    inputRange: [0, 1],
    outputRange: [0, width]
  })

  return <Animated.View
        style={{
          width: 1,
          height: 20,
          alignSelf: 'center',
          transform: [{ scaleX: animatedScale }],
          marginTop: 100,
          backgroundColor: 'red',
        }}
      />
}

export default CountDown;
```

1. You must see app crashing with current code with an error : 
```
RangeError: Property storage exceeds 196607 properties
```

2. In App.js change the `useNativeDriver` to `false` from `true` and verify app doesn't crash.

3. Also, try changing `TIMECONST` variable to `2000000` (basically remove one 0) with `useNativeDriver:true` and it should work properly.

4. You can also change the `jsEngine` to `jsc` to verify nothing crashes with jsc engine and it is related to hermes only.

## The Expected Behavior

No crashes with hermes.

**Comment by tmikov** [comment] 2023-02-17 19:46
Duplicate of https://github.com/facebook/hermes/issues/851

**Comment by tmikov** [comment] 2023-02-17 19:47
Also duplicate of https://github.com/facebook/hermes/issues/139

**Closed by tmikov** 2023-02-17 19:46 UTC
Labels: bug
