### ISSUE TITLE
BigInt support

### ISSUE THREAD

**Issue by likern** [facebook/hermes#510] opened 2021-05-08 20:10 UTC
## Problem

Hello ✋🏻 I've looked at documentation and source code and couldn't find `BigInt` type.
@tmikov Is it possible to add `BigInt` support?

**Comment by tmikov** [comment] 2021-05-08 21:52
@likern Yes, it is technically possible, though non-trivial. Unfortunately it is not on our short term roadmap since BigInt isn't used internally by our apps :-(

**Comment by ehsan6sha** [comment] 2021-07-23 03:06
> Unfortunately it is not on our short term roadmap sin

Can I ask what is used instead for internal apps? Or for internal apps there was no need for larger than nomral numbers?

**Comment by jzxchiang1** [comment] 2021-09-06 18:34
Bump, this is quite important for all crypto-related apps, which is the future anyways.

**Comment by jzxchiang1** [comment] 2021-11-13 19:43
Another friendly bump.

Facebook's recent rebranding to Meta underscores how important crypto-native mobile apps are and will continue to be. `BigInt` is an essential component of all cryptographic libraries, and mobile apps that create and validate signatures will need this support.

Flutter already has `BigInt` [support](https://api.flutter.dev/flutter/dart-core/BigInt-class.html) in Dart. Given that React Native is actively maintained by Meta, I assume they will need `BigInt` support in RN sooner rather than later. (Maybe not now but very soon...)

Right now, the workaround is to use JSC (limited to only iOS 14 and doesn't work on Android) or v8 (Android only). It's not ideal. Especially if Hermes is becoming the default JS engine.

**Comment by mrousavy** [comment] 2021-12-09 13:13
Hey! `BigInt` support is something I'm dealing with right now. I am using JS-based libraries such as `BigNumber`, but those aren't standardized and not very solid (in my opinion).

I've played around with trying to expose BigInt functionality through JSI to use C++ based big-number types, as well as using [the JSBI polyfill](https://github.com/GoogleChromeLabs/jsbi#why) - none of those support the `BigInt` literal notation (with the `n` suffix) though.

Would be great to have that baked into Hermes, I would love to have a shot at this myself if you can give me any pointers with relevant lines of code in this repo cc @tmikov

**Comment by tmikov** [comment] 2021-12-10 18:42
@mrousavy adding BigInt would touch a lot of components:
- the parser support for BigInt literals
- BigInt literals and instructions have to be added to the IR and the type system (for type inference)
- The bytecode file format has to be extended with a bigint table and instructions to load from it.
- HermesValue has to be extended with a new type tag and new "first-class" VM object has to be added. This is assuming that BigInt-s will always be kept on the heap. If small ones will be kept inline, it gets even more complicated. 
- The interpreter has to support the new instructions.
- All internal operations have to support the new type (like [add](https://github.com/facebook/hermes/blob/2b8b6a28f028391e80e649f6e5a9a10a637c29c4/lib/VM/Operations.cpp#L913), etc).
- It is not totally clear whether interpreter fast paths will be affected. Presumably if BigInt-s are kept only on the heap, they will be relatively slow so probably should be kept out of the fast paths.
- Lastly, JSLib (the standard JS library) has to extended.

Overall, I would say that it is a pretty involved project, but is certainly doable.

I am not actively working on Hermes anymore (I am currently focused on [Juno](https://github.com/facebook/hermes/tree/main/unsupported/juno), so I will let members of the Hermes team chime in here. cc: @neildhar

**Comment by neildhar** [comment] 2021-12-10 20:27
Unfortunately, implementing BigInt is still not on our immediate roadmap.

**Comment by jzxchiang1** [comment] 2021-12-29 07:22
If it's possible to bring up BigInt with the team and possibly prioritize it, that would be very much appreciated.

**Comment by likern** [comment] 2022-01-16 19:42
I want to point out that coming Temporal proposal (as I understand) is also using bigint, at least in polyfill.

**Comment by jzxchiang1** [comment] 2022-01-31 00:32
Here's another reason to support `BigInt` sooner rather than later:

The popular [web3.js](https://github.com/ChainSafe/web3.js) library is rewriting their library in modern TS and also [replacing](https://github.com/ChainSafe/web3.js/pull/4405#issuecomment-933116926) their `bignumber.js` dependency with native `BigInt`. This will be released in v4 soon (I believe this year, please correct me if I'm wrong). They are perhaps the most popular client-side library for connecting to Ethereum nodes.

**Comment by jzxchiang1** [comment] 2022-03-10 06:07
Is there any update on this? Thanks.

**Comment by krpeacock** [comment] 2022-05-02 17:39
We have many complaints about the lack of BigInt support for Internet Computer RN applications. Meta claims to be a crypto company - it is past time for RN to support BigInt

**Comment by jpporto** [comment] 2022-05-02 21:59
Hi everyone,

First of all, apologies for the delay in providing updates. Second, I am happy to say that we have been working on BigInts internally :). There should be some news around this soon! Please bear with us a little longer...

John Paul

**Comment by jzxchiang1** [comment] 2022-05-03 00:41
Looking forward to it.

**Comment by jzxchiang1** [comment] 2022-06-14 06:12
@jpporto Any news on this?

**Comment by jpporto** [comment] 2022-06-14 16:30
Hi @jzxchiang1,

We're still (actively) implementing BigInts. We're currently trying to minimize the overall impact of adding BigInt to the VM. It is our goal to ensure that adding BigInt doesn't cause any meaningful performance regressions in non-BigInt usage (e.g., Numbers).

Please bear with us a little longer.
John Paul

**Comment by brunomacf** [comment] 2022-06-23 14:34
Any updates on this? Anxious to have BigInt in hermes in order to allow crypto packages to work correctly in react native.

**Comment by jzxchiang1** [comment] 2022-06-28 01:57
I hate to ask this, but do you have any idea of a timeline for when BigInt will be launched?

**Comment by jpporto** [comment] 2022-06-28 18:20
I wish I had something more specific to say, but at this point I don't have any ETAs on when this support will land. :-(

**Comment by jpporto** [comment] 2022-07-08 20:09
Hi,

We have started the process of merging BigInt to hermes! It is a relatively large change (about 50 diffs), so it will be a while before everything makes to github. Hopefully everything will be ready by next week. :)

Thank you for your patience!

**Closed** 2022-07-11 13:39 UTC
Labels: enhancement

**Comment by jzxchiang1** [comment] 2022-07-12 05:12
Incredible thank you. Will it be released with the next version of Hermes/RN?

**Comment by paulmillr** [comment] 2022-07-19 01:30
For anyone's reading @jpporto 's comment that "bigints are unsuitable for crypto":

>We're working to minimize the impact adding BigInt has in the VM. I want to point out, however, that js BigInts are [not suitable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#cryptography) to crypto workloads. Your best option is to use a native crypto library, add js bindings, and call those from your JS app.

The advice is uninformed.

First of all, using native bindings does not guarantee any resistance against timing attacks. Because, JS runtime would still be there. JS is garbage-collected language. And there are no guarantees your uint8arrays or any other data structure would be cleaned properly at some point. If you want 100% constant-time code, your best bet is using low-level languages directly, but even [they are not the 100% solution](https://www.chosenplaintext.ca/open-source/rust-timing-shield/security): LLVM & other compilers could "optimize out" constant timeness.

Second, "Using a native crypto library" means users would need to run unsigned wasm binaries that may as well contain malware & trojans. Using pure javascript code allows every JS developer to verify the js code is indeed the one published on GitHub. Compiling C / Rust code to wasm produces huge binaries, commonly without using reproducible builds. The binaries may, or may not contain some dangerous garbage.

NPM got hacked. GitHub got hacked. Developer accounts can and will get hacked. Binaries will be replaced with malware without account owner's knowledge. So using bigints js library is not worse than a bytebuffer-based native solution. I think, it's better.

In fact, i've developed some bigint crypto libraries, which already received security audits.

**Comment by jpporto** [comment] 2022-07-19 02:49
Hi Paul,

Thank you for your feedback. I just wanted to point out that that's not my advice. Rather, I just quoted  the JS spec, _ipsis litteris_.

**Comment by shea256** [comment] 2022-07-19 04:14
@jpporto can you link to where it says that?

**Comment by ljharb** [comment] 2022-07-19 04:16
to clarify: MDN is not the spec, and not authoritative in any way.

**Comment by shea256** [comment] 2022-07-19 04:19
All I see is the MDN page which says the following:

> [Cryptography](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#cryptography)
The operations supported on BigInt values are not constant-time, and are thus open to [timing attacks](https://en.wikipedia.org/wiki/Timing_attack). JavaScript BigInts are therefore not well-suited for use in cryptography.

This statement has limited scope and isn’t relevant to the debate at hand, plus as @ljharb mentioned this is not authoritative.

**Comment by jpporto** [comment] 2022-07-19 05:04
(Apologies for the MDN vs. spec confusion. My bad.)

I should have started by saying I am no crypto expert. Far from it, I have no technical knowledge about the area as I prefer working on compilers and runtimes. 

While ecma262 doesn't mention crypto, the [bigint proposal](https://github.com/tc39/proposal-bigint) (which is arguably what I should have quoted before) [does](https://github.com/tc39/proposal-bigint#cryptography):

> The operations supported on BigInts are not constant time. BigInt is therefore [unsuitable for use in cryptography](https://www.chosenplaintext.ca/articles/beginners-guide-constant-time-cryptography.html).

I strongly believe in being transparent, so after having told krpeacock that BigInts were coming after [he specifically asked about the feature in the crypto context](https://github.com/facebook/hermes/issues/510#issuecomment-1115162735), I deemed prudent to come on the record with this pitfall. This doesn't mean I am telling anyone not to use BigInts for crypto -- I added the feature for the community to use it after all! :) --, just for those who do, to do so carefully.

**Comment by jzxchiang1** [comment] 2022-07-21 07:06
Thanks for getting this over the finish line. Although it may not seem like it, this is a big deal.

**Comment by roryabraham** [comment] 2022-08-04 23:20
Hi 👋 

Quick question: Does the new BigInt implementation in Hermes support the `12345n` syntax, or just the `BigInt(12345)` syntax?

**Comment by jpporto** [comment] 2022-08-05 00:16
Hi,

Hermes supports bigint literals, so you should be able to use 12345n. :)

John Paul

**Comment by paulmillr** [comment] 2022-08-05 01:08
I think you have some bugs with regards to bigint exponentiation 123n ** 256n. Has this been tested thoroughly?

**Comment by jpporto** [comment] 2022-08-05 01:18
Hi,

I am not sure if the testing that's been done would be considered extensively by you, so I'll refrain from commenting on that. However, I don't see any issues with 123n ** 456n (hermes and v8 agree on what the result). If you have an issue, please report it on a _new_ bug. I'll lock this one as this thread is too old, too long, and possibly include way too many people.

John Paul
