### ISSUE TITLE
base64 Performance

### ISSUE THREAD

**Issue by stephenheron** [facebook/hermes#111] opened 2019-09-18 11:42 UTC
Hi,

We recently upgraded our React Native application to 0.60 and enabled Hermes. We unfortunately noticed a performance regression. It took a bit of debugging to track down but I think I have found the source of the problem. 

One of the packages we use react-native-fs(https://github.com/itinance/react-native-fs) internally uses base64 (https://github.com/mathiasbynens/base64) to perform base64 encoding. I extracted the base64 encoding part from the library and made a little test case which shows the issue: https://gist.github.com/stephenheron/bd3e014ae46fe8a76ec0e7f68821584c

I ran the following commands:

`./hermes -emit-binary -out test.hbc test.js`
`time ./hermes test.hbc`

and it produced the following output:
`real 0m2.160s`
`user 0m2.020s`
`sys	 0m0.118s`

If we run the same script using node it is much faster:
`real 0m0.094s`
`user 0m0.070s`
`sys	0m0.023s`

This feels like quite a large performance difference, in our real app if we switch off Hermes our app is much faster. I also tried upgrading Hermes to 0.2.1 to see if the regression disappeared but unfortunately the issue still remains.  

If you need anymore information the please let me know and I will do my best to help. 

Thanks,
Stephen

**Comment by avp** [comment] 2019-09-19 21:18
The reason that your example code here is running slowly is that it builds a string incrementally using `+=`, which requires copying the existing string to the result of the concatenation. Hermes is inefficient in this particular use case because it does not have an implementation of ropes. Note that if `output` is initialized to `[]`, `.push()` is called instead of `+=`, and `output.join('')` is used as the final result, the complexity of the loop drops from quadratic to linear and Hermes no longer takes multiple seconds to run the example code snippet.

However, we recognize that this string concatenation pattern is expected to be fast in the JavaScript that developers typically write. We're actively investigating ways to add ropes to Hermes in a clean and efficient manner.

**Comment by marf** [comment] 2019-09-23 13:12
Hello @avp, I have the same problem in my app since I use the react-native-fs package.
Any news on how I can handle this slowness or mitigate it?
I cannot modify the react-native-fs package.

Thank you

**Comment by Buthrakaur** [comment] 2019-10-15 12:42
In most programming ecosystems string concatenation is a performance issue if done naively using `+=`  approach so this is the result :( The same problem is also in https://github.com/mathiasbynens/utf8.js which is also used by react-native-fs. For base64 there's and alternative library https://github.com/beatgammit/base64-js , which deals with string concatenation correctly. The option for now is to patch utf8 + base64 libs :/

**Comment by tmikov** [comment] 2019-10-15 15:46
We are working on a solution inside Hermes, so things should get better soon.

**Comment by marf** [comment] 2019-10-15 16:47
Awesome @tmikov! Do you have an estimation on when this patch will be published?

**Comment by tmikov** [comment] 2019-10-16 03:31
It is undergoing testing right now, so I expect within a week or so, hopefully sooner.

**Comment by enahum** [comment] 2019-10-23 21:03
@tmikov can you share any progress on this?

**Comment by tmikov** [comment] 2019-10-25 02:43
It is still failing some tests on Windows, but almost there.

**Comment by tmikov** [comment] 2019-10-28 21:47
The improvement landed in fc2674b1ed207fb5967f75d1159e5f0b8c46fa8d . Note that since it is not part of a release yet, in order to try it you need to manually build Hermes and RN.

**Closed by tmikov** 2019-10-28 21:48 UTC
Labels: enhancement

**Comment by stwiname** [comment] 2019-10-29 21:55
Is there any sort of release schedule? When would we expect to see a release with this in it?

**Comment by tmikov** [comment] 2019-10-30 00:43
Hermes releases are synchronized with RN releases because there is an ABI dependency between them. I will check whether there will be a RN cut soon.

**Comment by florinvasilevilsan** [comment] 2019-11-15 17:00
Any news on this?

**Comment by tmikov** [comment] 2019-11-15 19:33
Again, the fix has already been committed in Hermes, but we don't control the React Native release schedule. It is an unfortunate situation and we understand how frustrating it is. It is also disappointing to us, since we have added many improvements that we want people to use.

It is technically possible to build RN from master locally and use that, but it is not easy.

We are also discussing the possibility of using a RN patch release, but there is some understandable resistance to that, since upgrading to an ABI-incompatible version of Hermes feels more than a patch.

**Comment by marf** [comment] 2020-03-28 21:35
Hello, I have upgraded to RN 0.62 but the performance degradation with Hermes enabled still persists.

**Comment by tmikov** [comment] 2020-03-31 00:38
@marf do you have a sample demonstrating the performance problem?

**Comment by marf** [comment] 2020-03-31 09:08
Unfortunately I tested it only on our project which is quite big, but I will try to create a sample once I will found if the problem is the `react-native-fs` or other packages.

**Comment by tusharmutreja200** [comment] 2022-04-06 10:55
@all is anyone have the solution for this issue?

**Comment by tusharmutreja200** [comment] 2022-04-06 10:56
hey @stephenheron [stephenheron](https://github.com/stephenheron) is there any update, did you resolve this issue?

**Comment by tusharmutreja200** [comment] 2022-04-07 06:39
@tmikov please update, is this issue resolved as I am still facing this issue.
RN version: 0.66
Hermes: v0.9.0

**Comment by tmikov** [comment] 2022-04-07 13:47
@tusharmutreja200 Update on what? What issue? 

The issue reported in the post was resolved in Oct 2019. Right now,`time hermes` and `time node` of the test case from the original post take the same time. Later someone complained that they were still having a problem and I asked for more information on Mat 30 2020, more than two years ago. I haven't received a response. 

I am not longer working on Hermes, but if you can come up with a minimal test case demonstrating the problem, I will gladly pass it on to the Hermes team.

**Comment by tusharmutreja200** [comment] 2022-04-12 10:19
@tmikov Thanks for the reply.

When we enable the Hermes in our application, then the Write operation of RNFS starts getting slow and takes more time to execute.

Please help me out with your input in it.

reference code : `async createSyncedBackup(user, url) {
        RNFS.mkdir(PATH);
        RNFS.mkdir(PATH_BACKUP);
        RNFS.mkdir(PATH_BACKUP_TEMP);
        let json = await this.getJsonData(user.value.lastLoginTime) // This will fetch jsondata after the lastLoginTime.
        if (!json) return
        let isEncryptionSuccessful = true;
	  try {
		    await RNFS.writeFile(PATH_BACKUP_TEMP + '/logs.json', encryptedResult.toString(), 'utf8');
		} catch (error) {
		    isEncryptionSuccessful = false
		}
		//Send data in plain text format to server,sync shouldn't be stopped if encryption failed
		if (!isEncryptionSuccessful) {
		    //Writing Object to File at TEMP location
        		await RNFS.writeFile(PATH_BACKUP_TEMP + '/logs.json', json, 'utf8');
		} 
        
        const backupFileName = this.getBackupFileName(user.value, false, url) // this will get the backup file name.
        //Creating ZIP file
        const targetPath = PATH_BACKUP + '/' + backupFileName
        const sourcePath = PATH_BACKUP_TEMP
        await zip(sourcePath, targetPath);
        await RNFS.unlink(PATH_BACKUP_TEMP)
        return backupFileName

    }`

**Comment by tmikov** [comment] 2022-04-12 15:18
> await RNFS.writeFile(PATH_BACKUP_TEMP + '/logs.json', encryptedResult.toString(), 'utf8');

@tusharmutreja200 how is this reference code is related to base64 performance?

**Comment by tusharmutreja200** [comment] 2022-04-18 10:57
@tmikov RNFS.write internally use base64 encoding/decoding operations.

`writeFile(filepath: string, contents: string, encodingOrOptions?: any): Promise<void> {
    var b64;

    var options = {
      encoding: 'utf8'
    };

    if (encodingOrOptions) {
      if (typeof encodingOrOptions === 'string') {
        options.encoding = encodingOrOptions;
      } else if (typeof encodingOrOptions === 'object') {
        options = {
          ...options,
          ...encodingOrOptions
        };
      }
    }

    if (options.encoding === 'utf8') {
      b64 = base64.encode(utf8.encode(contents));
    } else if (options.encoding === 'ascii') {
      b64 = base64.encode(contents);
    } else if (options.encoding === 'base64') {
      b64 = contents;
    } else {
      throw new Error('Invalid encoding type "' + options.encoding + '"');
    }

    return RNFSManager.writeFile(normalizeFilePath(filepath), b64, options).then(() => void 0);
  }`
