### ISSUE TITLE
Crash on try catch saying that the error in the catch does not exist

### ISSUE THREAD

**Issue by rogeriomoura** [facebook/hermes#864] opened 2022-12-07 21:43 UTC
## Bug Description

![image](https://user-images.githubusercontent.com/40436363/206298972-b75ffe9b-19cd-4e24-9e7b-bd18ddd524e1.png)
```
try {
      const result = await resolvePromise(promise);
      isCurrentlyMounted &&
        debounceSetState((prev) => ({
          ...prev,
          fetching: false,
          loading: false,
          result,
        }));
    } catch (error) {
      // const catchError = error;
      isCurrentlyMounted &&
        debounceSetState((prev) => ({
          ...prev,
          fetching: false,
          loading: false,
          error: error as Error,
        }));
    }
```

When trying to run the above code, I get the error saying that 'error' does not exist, if I create the variable 'catchError' and assign the error to it, then it goes through without a problem.

I started seeing this issue after I migrated to react native 0.70.6 and started using hermes.
This is happening on a iOS simulator.

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.70.6
React Native version (if any): 0.70.6
OS version (if any): iOS 16.0
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): x86_64

## Steps To Reproduce

1. Try to use the catch error inside a function with a different scope

**Comment by rogeriomoura** [comment] 2022-12-08 17:19
@tmikov here is what Babel transformed it to:
```
try {
          var data = yield resolvePromise(promise);
          isCurrentlyMounted && setState(function (prev) {
            return Object.assign({}, prev, {
              loading: false,
              data: data
            });
          });
        } catch (error) {
          isCurrentlyMounted && setState(function (prev) {
            return Object.assign({}, prev, {
              loading: false,
              error: error
            });
          });
        }
      });
```

**Comment by tmikov** [comment] 2022-12-08 18:04
@rogeriomoura this lowering doesn't seem to correspond exactly to the original code: `fetching` is missing, `debounceSetState()` has been changed. Can you confirm that this is *exactly* what Hermes is running when the problem occurs?

**Comment by rogeriomoura** [comment] 2022-12-08 18:42
@tmikov 
Yeah, that's the exact code, I'm not sure why the debauncing part of it is not there.
Just for reference, here is the implementation of that `debaunceSetState`:
```
const debounceSetState = debounce(setState, 100);
```

**Comment by tmikov** [comment] 2022-12-08 18:54
@rogeriomoura are you saying that your transformation pipeline **deleted** the property `fetching` and changed the call `debounceSetState()` to `setState()`?

**Comment by rogeriomoura** [comment] 2022-12-08 19:33
@tmikov my bad!
We have a library that imports a `useAsync` but it is not our implementation, here is the right one:
```
        try {
          var result = yield resolvePromise(promise);
          isCurrentlyMounted && debounceSetState(function (prev) {
            return Object.assign({}, prev, {
              fetching: false,
              loading: false,
              result: result
            });
          });
        } catch (error) {
          isCurrentlyMounted && debounceSetState(function (prev) {
            return Object.assign({}, prev, {
              fetching: false,
              loading: false,
              error: error
            });
          });
        }
```

**Comment by tmikov** [comment] 2022-12-08 21:48
@rogeriomoura I couldn't reproduce your problem by running the following code:
```
var gPrev = {}
var doErr = 0;

function debounceSetState(func) {
    gPrev = func(gPrev);
    if (++doErr == 1)
        throw Error("fake errror");
}

function *bad() {
    try {
      var result = yield 10;
      debounceSetState(function (prev) {
        return Object.assign({}, prev, {
          fetching: false,
          loading: false,
          result: result
        });
      });
    } catch (error) {
      debounceSetState(function (prev) {
        return Object.assign({}, prev, {
          fetching: false,
          loading: false,
          error: error
        });
      });
    }
}

it = bad();
it.next();
it.next("fake result");
print(JSON.stringify(gPrev));
```

I am sorry, but without a concrete repro, there isn't anything more we can do. In order to constructively investigate a compiler or runtime bug, we need a minimal reproduction case: a small piece of code to feed directly into Hermes, producing the incorrect result.

For the time being I am removing the "bug" tag, but feel free to restore it when you have the repro.

**Comment by rpopovici** [comment] 2023-01-27 15:03
I have a similar problem in react-native. Looks like it's an older bug https://github.com/facebook/react-native/issues/18087

Looks like the native exception is not properly handled in JS if you try to fetch from a malformed url:

```
try {
    const res = await fetch("https://malformed/api");
} catch (err) {
    // throw err; // this does not work. err is undefined

    // throw { ...err } // this does not work. err is undefined 

    // unpacking and recreating the error object works :)
    const { name, message, stack, status } = err;
    throw { name, message, stack, status };
}
```

Strangely enough, if you unpack the error object and re-throw a new error object, then it works

**Comment by tmikov** [comment] 2023-01-27 19:03
@rpopovici can you provide the transpiled version of the above code? Also, does `print(err)` output `undefined`?

**Comment by rpopovici** [comment] 2023-01-28 14:57
@tmikov this is how the transpiled code looks like:

```
  var fetchData = function () {
    var _ref4 = _$$_REQUIRE(_dependencyMap[9])(function* (input, init) {
      try {
        var res = yield fetch("https://malformed/api");
      } catch (err) {
        console.log("Error: " + JSON.stringify(err));
        console.log(err.toString());
        console.log(err);
        throw err;
      }
    });
    return function fetchData(_x3, _x4) {
      return _ref4.apply(this, arguments);
    };
  }();
  exports.fetchData = fetchData;
```

`console.log("Error: " + JSON.stringify(err))` returns `Error: {}`
`console.log(err.toString())` returns `TypeError: Network request failed`
`console.log(err)` returns `[TypeError: Network request failed]`
`flipper` breakpoint returns `undefined`

**Comment by tmikov** [comment] 2023-01-28 15:48
@rpopovici, thanks! 

Hmm, to me this seems to show that `err` has the correct value (not 'undefined'), but there might be a problem with displaying it in the debugger? The latter wouldn't surprise me, since we have to play some scoping tricks with the catch variable even in ES5. It is conceivable that we have a bug in accessing the value of a catch variable from a debugger.

Can you try assigning it to a different variable and trying to view that from the debugger (e.g. `var xxx = err;`)?

**Comment by rpopovici** [comment] 2023-01-28 15:58
Assigning `err` to another variable works. I can see the error object in flipper:

```
jsEngine: "hermes"
message: "Network request failed"
stack: "TypeError: Network request failed...
```

**Comment by tmikov** [comment] 2023-01-28 16:45
@rpopovici I was able to reproduce the problem with the `hdb` tool and this simple source:

```
function foo(a) {
    try {
        throw a+10;
    } catch (err) {
        print(err);
        var xxx = err;
        debugger;
    }
}

foo(5);
```

And the following debugging session:
```
hdb catch.js
15
Break on 'debugger' statement in foo: catch.js[2]:7:9
(hdb) exec a
5
(hdb) exec xxx
15
(hdb) exec err
Exception: ReferenceError: Property 'err' doesn't exist
  0: eval: JavaScript:1:1
  1: foo: catch.js:7:9
  2: global: catch.js:11:4
Thrown value is: { message: Property 'err' doesn't exist }
(hdb) info variables
this = undefined
 0:          a = 5
 0:        xxx = 15
 0: ?anon_0_err = 15
 ```
 
 Clearly, the debugger doesn't know about the variable `err`.
 
 It doesn't seem like this is the same problem as the one reported by @rogeriomoura, but this is a legitimate bug. I am opening a new issue for tracking it.

**Comment by woowalker** [comment] 2023-12-20 02:05
in my case, i require none exist file, it still crash
```
try {
  require('module')
} catch (e) {
  console.err(e)
}
```

**Comment by tmikov** [comment] 2023-12-20 02:35
@woowalker this is not enough information for us to work with. What do you mean by "crash"? Do you have a small reproducible sample that can be executed in the Hermes CLI?

**Comment by woowalker** [comment] 2023-12-20 06:40
@tmikov thanks for your quickly response. what i mean is try catch seems cannot catch require none exist file error, it cause program crash, i try from new project, React Native verison is 0.73.1; run in android emulator

- start a new project
```
npx react-native init MyApp --template react-native-template-typescript
```
- require none exist file, try catch cannot catch the error
![image](https://github.com/facebook/hermes/assets/7894779/6478f925-1a9a-43fa-9478-87f5dda9f86b)

- red screen, and even release to an apk, it cannot open just crash
![image](https://github.com/facebook/hermes/assets/7894779/88c6c03d-e34c-44ef-b706-181a8c9735f8)
![image](https://github.com/facebook/hermes/assets/7894779/de86f529-8973-46bd-a0c8-0a2dbf2ee02d)

**Comment by martinbigio** [comment] 2023-12-20 16:47
@woowalker the example you shared is unrelated to the GH issue. I don't think the `require` (defined on RN itself) is expected to throw. The "red box error" you're seeing is triggered by the require function call itself. In other words, the call finished gracefully after pushing a view to display the error. `require` has different semantics that `fopen`. Maybe that's where the confusion is coming from?

**Comment by woowalker** [comment] 2023-12-21 02:45
@martinbigio not much understand, i just want to figure out why try catch cannot caught the require error, i can`t use require to detect whether module is exist, make me crazy.

**Comment by martinbigio** [comment] 2023-12-21 19:52
I work on Hermes (not RN) but `require` is not meant to be called with a JS module that doesn't exist. Please look at alternative ways to achieve what you're trying to do. I also kindly ask to keep this GH issue on topic - the issue you brought up is unrelated to it. Thanks!

**Comment by tmikov** [comment] 2024-10-18 16:58
Closing, since no repro for the original issue.

**Closed by tmikov** 2024-10-18 16:58 UTC
Labels: need more info, need-repro
