### ISSUE TITLE
hermes

### ISSUE THREAD

**Issue by SKB-TECH** [facebook/hermes#875] opened 2022-12-30 07:58 UTC
RangeError: Property storage exceeds 196607 properties, js engine: hermes

**Comment by tmikov** [comment] 2022-12-31 02:39
This is by design. Please, make sure to perform a search before creating a new issue. This is a duplicate of 
- https://github.com/facebook/hermes/issues/139
- https://github.com/facebook/hermes/issues/752
- https://github.com/facebook/hermes/issues/851

**Closed by tmikov** 2022-12-31 02:39 UTC
Labels: bug, wontfix
