### ISSUE TITLE
Parse hermes stacktrace

### ISSUE THREAD

**Issue by swabbass** [facebook/hermes#276] opened 2020-06-22 22:43 UTC
How do you manage to parse stack traces like this ? is there a doc about it 

```
 anonymous@1:557290
    v@1:550772
    d@1:550459
    o@1:550087
    anonymous@1:557270
    v@1:550772
    d@1:550416
    o@1:550087
    global@1:549807
```

**Comment by willholen** [comment] 2020-06-25 00:10
This is unfortunately underdocumented at the moment. You can symbolicate it using the `metro-symbolicate` package (installed by default in the RN template project), and pass it the generated source map and a stack trace:

    npx metro-symbolicate android/app/build/generated/sourcemaps/react/release/index.android.bundle.map < stacktrace.txt

Note:

* The build process generates multiple source maps, one from the packager, one from the compiler, and one that merges the previous two. You have to use the merged map.
* If `metro-symbolicate` exits immediately with success, make sure the input comes from a pipe or redirection, and not from a terminal. 
* The stack trace can be clean like yours, or in the midst of other information as when piped directly from `adb log`

**Closed by willholen** 2020-06-25 00:10 UTC

**Comment by swabbass** [comment] 2020-06-25 09:33
> This is unfortunately underdocumented at the moment. You can symbolicate it using the `metro-symbolicate` package (installed by default in the RN template project), and pass it the generated source map and a stack trace:
> 
> ```
> npx metro-symbolicate android/app/build/generated/sourcemaps/react/release/index.android.bundle.map < stacktrace.txt
> ```
> 
> Note:
> 
> * The build process generates multiple source maps, one from the packager, one from the compiler, and one that merges the previous two. You have to use the merged map.
> * If `metro-symbolicate` exits immediately with success, make sure the input comes from a pipe or redirection, and not from a terminal.
> * The stack trace can be clean like yours, or in the midst of other information as when piped directly from `adb log`

Life saver, thx a lot :]

**Comment by willholen** [comment] 2020-07-30 17:16
As an update, this is now part of the official React Native docs: https://reactnative.dev/docs/next/symbolication

**Comment by afilp** [comment] 2022-02-08 12:11
When I run it, I get an empty `stacktrace.txt`. Most likely because I run it from windows terminal or WSL bash? 
How can I "pipe" the command? Not sure what the problem is here. Thanks!

**Comment by irisjae** [comment] 2023-12-02 08:05
I think the docs would be much more helpful if it included the above information regarding which of the source maps to use. Perhaps that should be added?
