### ISSUE TITLE
Empty string toLocaleLowerCase() / toLocaleUpperCase() failed

### ISSUE THREAD

**Issue by alexkrav** [facebook/hermes#687] opened 2022-03-03 18:34 UTC
## Bug Description
 JS toLocaleLowerCase() / toLocaleUpperCase()  for empty string returns unreadable string with length 98.

- [ +] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.9.0
React Native version (if any): 0.66
OS version (if any): Android 11
Platform (ARMv8):

## Steps To Reproduce

1. execute  toLocaleLowerCase() / toLocaleUpperCase() on empty string
2.

code example:
```
    const empty = '';
    console.log(
      `empty.toLocaleLowerCase().length = ${
        empty.toLocaleLowerCase().length
      }; empty.toLocaleLowerCase()=|${empty.toLocaleLowerCase()}|`
    );
```
In logcat:
```
2022-03-03 10:26:39.697 23086-23307/com.evernote I/ReactNativeJS: empty.toLocaleLowerCase().length = 98; 
empty.toLocaleLowerCase()=|覮m
```
## The Expected Behavior
toLocaleLowerCase() / toLocaleUpperCase()  for empty string should return empty string

**Comment by neildhar** [comment] 2022-03-04 00:21
This looks like a duplicate of https://github.com/facebook/hermes/issues/602, please feel free to reopen it if you're still seeing the issue in Hermes 0.11/RN0.68

**Closed by neildhar** 2022-03-04 00:21 UTC
Labels: bug
