### ISSUE TITLE
Assertion failed: (!opFlags.getMustExist() && "MustExist cannot be used with Proxy objects") in function putNamedWithReceiver_RJS, file JSObject.cpp

### ISSUE THREAD

**Issue by JimWongM** [facebook/hermes#1007] opened 2023-05-22 08:40 UTC
## Bug Description
Hermes crash when I run test.js below.
```
Assertion failed: (!opFlags.getMustExist() && "MustExist cannot be used with Proxy objects"), function putNamedWithReceiver_RJS, file JSObject.cpp, line 1388.
Process 16532 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #4: 0x000000010025d934 hermes`hermes::vm::JSObject::putNamedWithReceiver_RJS(selfHandle=Handle<hermes::vm::JSObject> @ 0x000000016fdf9368, runtime=0x000000010380a400, name=(id_ = 635), valueHandle=Handle<hermes::vm::HermesValue> @ 0x000000016fdf9350, receiver=Handle<hermes::vm::HermesValue> @ 0x000000016fdf9340, opFlags=PropOpFlags @ 0x000000016fdf926c) at JSObject.cpp:1386:7
   1383     }
   1384 
   1385     if (LLVM_UNLIKELY(desc.flags.proxyObject)) {
-> 1386       assert(
   1387           !opFlags.getMustExist() &&
   1388           "MustExist cannot be used with Proxy objects");
   1389       CallResult<bool> setRes = JSProxy::setNamed(
Target 0: (hermes) stopped.
```

backtrace:
```
    frame #0: 0x00000001962a2868 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x00000001962d9cec libsystem_pthread.dylib`pthread_kill + 288
    frame #2: 0x00000001962122c8 libsystem_c.dylib`abort + 180
    frame #3: 0x0000000196211620 libsystem_c.dylib`__assert_rtn + 272
  * frame #4: 0x000000010025d934 hermes`hermes::vm::JSObject::putNamedWithReceiver_RJS(selfHandle=Handle<hermes::vm::JSObject> @ 0x000000016fdf9368, runtime=0x000000010380a400, name=(id_ = 635), valueHandle=Handle<hermes::vm::HermesValue> @ 0x000000016fdf9350, receiver=Handle<hermes::vm::HermesValue> @ 0x000000016fdf9340, opFlags=PropOpFlags @ 0x000000016fdf926c) at JSObject.cpp:1386:7
    frame #5: 0x00000001002dafd4 hermes`hermes::vm::JSObject::putNamed_RJS(selfHandle=Handle<hermes::vm::JSObject> @ 0x000000016fdfc1d8, runtime=0x000000010380a400, name=(id_ = 635), valueHandle=Handle<hermes::vm::HermesValue> @ 0x000000016fdfc1c0, opFlags=PropOpFlags @ 0x000000016fdf9384) at JSObject.h:1950:10
    frame #6: 0x00000001001f0a18 hermes`hermes::vm::CallResult<hermes::vm::HermesValue, (hermes::vm::detail::CallResultSpecialize)2> hermes::vm::Interpreter::interpretFunction<false, false>(runtime=0x000000010380a400, state=0x000000016fdfdb30) at Interpreter.cpp:2447:9
    frame #7: 0x00000001001e7560 hermes`hermes::vm::Runtime::interpretFunctionImpl(this=0x000000010380a400, newCodeBlock=0x00006000029040e0) at Interpreter.cpp:825:12
    frame #8: 0x0000000100209860 hermes`hermes::vm::Runtime::interpretFunction(this=0x000000010380a400, newCodeBlock=0x00006000029040e0) at Interpreter.cpp:833:10
    frame #9: 0x00000001002e3320 hermes`hermes::vm::Runtime::runBytecode(this=0x000000010380a400, bytecode=nullptr, flags=RuntimeModuleFlags @ 0x000000016fdfdedf, sourceURL=(Data = "", Length = 0), environment=Handle<hermes::vm::Environment> @ 0x000000016fdfe040, thisArg=Handle<hermes::vm::HermesValue> @ 0x000000016fdfe030) at Runtime.cpp:1064:11
    frame #10: 0x00000001005488ec hermes`hermes::vm::Runtime::runBytecode(this=0x000000010380a400, bytecode=nullptr, runtimeModuleFlags=RuntimeModuleFlags @ 0x000000016fdfe08f, sourceURL=(Data = "", Length = 0), environment=Handle<hermes::vm::Environment> @ 0x000000016fdfe2e0) at Runtime.h:277:12
    frame #11: 0x0000000100547fa4 hermes`hermes::(anonymous namespace)::executeHBCBytecodeImpl(bytecode=nullptr, options=0x000000016fdfed40, filename="") at ConsoleHost.cpp:331:53
    frame #12: 0x0000000100547b30 hermes`hermes::executeHBCBytecode(this=0x000000016fdfe6e0)::$_2::operator()() const at ConsoleHost.cpp:417:12
    frame #13: 0x000000010053b458 hermes`decltype(f=0x000000016fdfe6e0)) hermes::(anonymous namespace)::maybeCatchException<hermes::executeHBCBytecode(std::__1::shared_ptr<hermes::hbc::BCProviderBase>&&, hermes::ExecuteOptions const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*)::$_2>(hermes::executeHBCBytecode(std::__1::shared_ptr<hermes::hbc::BCProviderBase>&&, hermes::ExecuteOptions const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*)::$_2 const&) at ConsoleHost.cpp:253:10
    frame #14: 0x000000010053b430 hermes`hermes::executeHBCBytecode(bytecode=nullptr, options=0x000000016fdfed40, filename="") at ConsoleHost.cpp:416:10
    frame #15: 0x0000000100006558 hermes`executeHBCBytecodeFromCL(bytecode=nullptr, info=0x000000016fdfef48) at hermes.cpp:131:15
    frame #16: 0x0000000100005ae0 hermes`main(argc=2, argv=0x000000016fdff500) at hermes.cpp:204:16
    frame #17: 0x0000000195fafe50 dyld`start + 2544

```

Hermes version: 4b153a8cf416af7ea6f9b8292816657e52fd2198
React Native version (if any):
OS version (if any):
Platform: x86_64

## Steps To Reproduce
Hermes should be compiled in Debug mode.
```./hermes test.js```

code example:
```
function f() {
    'use strict';
    v = 2
}
const v9 = new Proxy(Object.prototype, {});
v9.__proto__ = v9;
f();
```

## The Expected Behavior

This script should not crash hermes.

**Comment by tmikov** [comment] 2023-05-22 15:08
Duplicate of https://github.com/facebook/hermes/issues/379

**Closed by tmikov** 2023-05-22 15:08 UTC
Labels: bug, duplicate
