### ISSUE TITLE
'show source' does not work on first run when debugging

### ISSUE THREAD

**Issue by nouvist** [facebook/hermes#612] opened 2021-10-19 10:38 UTC
## Bug Description

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC
- [x] I have follow documentation about how to enable Hermes engine on React Native 

Hermes version: 0.9.0
React Native version (if any): 0.66.1
OS version (if any): Android 11
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): arm32_64binder

## Steps To Reproduce

1. Create toString-able function
2. Run `react-native android`

code example:
```javascript
function test() {
  'show source';
  alert(1337);
}
console.log(test.toString());
```

## The Expected Behavior
The `Function.prototype.toString()` should return string of its function script.

## The Actual Behavior
It return `function() { [bytecode] }` instead. But, after I change some line, it does work. So, it is works after HMR on the file that using `'show source'`, not on first run / after manual reloading / HMR on other file.

But when I build as release variant, it works as expected.

**Comment by neildhar** [comment] 2021-10-20 23:10
Hi @nouvist, thanks for reporting this bug, I've confirmed that I can reproduce it as described. In a debug build it initially just prints `function() { [bytecode] }`, but changing code and reloading or using a release build causes the function source to show up correctly.

**Comment by chiubaka** [comment] 2021-11-11 09:21
Also noticing this as I attempt to upgrade to RN 0.65.2 to enable Hermes as a prerequisite to `react-native-vision-camera` and `react-native-reanimated` v2. Works fine when I create a release build, but doesn't work when I run in debug / development.

I'm not able to get the expected behavior after changing a line and allowing the application to reload. Guessing I may need to upgrade to Hermes 0.9.0 for that.

I also tried to use `hermes-release.aar` rather than `hermes-debug.aar` in debug builds, but that didn't seem to solve the issue.

Any news on a potential fix for this?

**Comment by nouvist** [comment] 2021-11-19 02:40
just want to update this issue. I do not understand about how the engine works and how it could be fixed. but, I do have my own solution to this.

my current approach is separate string-able function to a different file with custom extension in order to prevent metro resolve this as a javascript. then, add the custom extension to assetExts, so metro will resolve this as an asset. then, read the file using react-native-fs. optionally, add alias on vscode, so vscode can understand what language it is even in custom extension.

may not the best approach tho. but, works with autocomplete.

**Comment by PierreVanobbergen** [comment] 2021-12-07 09:52
Same problem on my side.
The first run in debug will always return `function() { [bytecode] }`, and also after a new JS bundle download.
To fix in debug, you just need to hot reload the file containing the `.toString` method, and it will work fine 

Works in release tho.

**Comment by chrfalch** [comment] 2022-02-10 19:07
Upvoting this issue - its a bit of a bummer now that the functionality for `toString` is implemented and available.

**Comment by AlenToma** [comment] 2022-06-17 04:42
Waking when I created a new expo app, but when I implemented it in my existing old expo app it did not work.

Have not try in release yet.

**Comment by nouvist** [comment] 2022-07-12 09:07
I am nothing near as familiar to low level programming. sorry that I couldn't contribute any code to this repo.
but I made a [Babel plugin](https://github.com/nouvist/babel-plugin-show-source#readme) for `"show source"` directive. me myself is using this for now as temporary solution to this issue.

but currently, this plugin will throw an error when using it on function declaration. so, if you wanna use it, use arrow function or function expression instead. and also, Hermes behavior will override the `.toString()` of any function that have `"show source"` directive on it, which is also has an impact to this plugin. so, if you wanna use this plugin, you should change the directive to other than `"show source"` to prevent conflicting with Hermes native implementation.

**Comment by jaredh159** [comment] 2023-03-02 20:26
I can confirm the behavior is the same on ios. Initially renders with `[bytecode]`, but hmr triggers correct behavior. Also works in release mode.

**Comment by paradite** [comment] 2023-08-19 08:52
Well this has just became a problem again after upgrading Expo SDK to 48 and React Native to `0.71.8`, where HMR doesn't seem to work as expected and the whole app got reloaded when I tried to trigger a HMR.

**Comment by Fuzzyma** [comment] 2023-12-13 19:54
@nouvist also solved another problem with its solution: the transpilation to es5 which broke my code since it introduced helper functions that are not available in the function itself. Thanks so much! Only had to remove the typescript types (wrote another hacky babel plugin for that)

**Comment by tmikov** [comment] 2024-12-17 19:19
I am applying the label `fixed-in-sh`, meaning that this has been fixed in Static Hermes but is "Wontfix" in Hermes. We need this label because technically SH has not been released yet, but at the same time we don't want to keep issues like this open.

**Closed by tmikov** 2024-12-17 19:19 UTC
Labels: bug, fixed-in-sh
