### ISSUE TITLE
The Math.random implementation in Hermes is collision prone for the App use case

### ISSUE THREAD

**Issue by psaha-rbi** [facebook/hermes#1169] opened 2023-10-19 21:10 UTC
## Bug Description

The implementation is 
```
CallResult<HermesValue> mathRandom(void *, Runtime &runtime, NativeArgs) {
  RuntimeCommonStorage *storage = runtime.getCommonStorage();
  if (!storage->randomEngineSeeded_) {
    std::minstd_rand::result_type seed;
    seed = std::random_device()();
    storage->randomEngine_.seed(seed);
    storage->randomEngineSeeded_ = true;
  }
  std::uniform_real_distribution<> dist(0.0, 1.0);
  return HermesValue::encodeUntrustedNumberValue(dist(storage->randomEngine_));
}
```
As you can see, it uses `std::random_device()` as seed. It is an unsigned int and therefore there are only about 4B possible values.  There is a 71% chance of a single collision if you generate 100k values using the [Birthday problem formulation](https://en.wikipedia.org/wiki/Birthday_problem#Approximations). So many different instances of this will go through the exact same sequence. While this is not used for security, this is also unusable for things like UUID v4 generation since there will be tons of collisions.

Please consider using a much larger seed space - ideally, 100+ bits. A simple way would be to concatenate multiple outputs from std::random_device().

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: latest
React Native version (if any): all
OS version (if any): all
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): all

## Steps To Reproduce

Theoretical but we have seen collisions matching the birthday problem formula out in the wild.

code example:

## The Expected Behavior
Much harder to produce collisions.

**Comment by tmikov** [comment] 2023-10-19 21:31
Hi, I removed the "bug" label, since this not a bug - EcmaScript specifies it as implementation defined and puts no requirements for its "randomness".

Can you provide links to the relevant implementations in v8 or JSC? If we are to change this, we should probably match theor behavior. 

The best way to improve this would probably be to submit a PR.

**Comment by tmikov** [comment] 2023-10-19 21:39
Also, can you please clarify your 4B values comment. That is just the seed, which is used once. How does it affect the quality of the values that are generated after?

**Comment by psaha-rbi** [comment] 2023-10-19 22:10
@tmikov If two instances of the  PRNG are seeded with the same value then they'll generate the same sequence of pseudo-random values. In this case, let's say you have 1M Hermes instances. In about 7 of them, the `randomEngine_` will have the same seed and therefore end up generating the same sequence of "random" values. Now imagine an app that starts up and generates a sequence of UUID v4s. In 7 out of that million instances, you get the exact same sequence of uuid v4s.

[Here's a good blog post](https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d) that explains similar issues much better than I can

**Comment by psaha-rbi** [comment] 2023-10-19 22:34
> Hi, I removed the "bug" label, since this not a bug - EcmaScript specifies it as implementation defined and puts no requirements for its "randomness".
> 
> Can you provide links to the relevant implementations in v8 or JSC? If we are to change this, we should probably match their behavior.
> 
> The best way to improve this would probably be to submit a PR.

I could not find the JSC implementation but [here's the v8 one](https://github.com/v8/v8/blob/1fbd008a40d8d751b58937cb821285400309cd13/src/numbers/math-random.cc#L47)
As you can see, it uses a 64 bit seed - so much less chance of a collision if the seeds are uniformly distributed.

**Comment by johnculviner** [comment] 2023-10-20 02:06
I think it's important to note that this issue is prone to happening specifically because this [issue is deemed out of scope](https://github.com/facebook/hermes/issues/915). There isn't a built in cryptographically secure mechanism to PRNG which can cause collisions when using libraries that may fall-back to `Math.random()` like https://www.npmjs.com/package/uuid . I think increasing the seed-space should be done at a minimum to reduce likelihood of collisions which we have personally observed using UUID with it's `Math.random()` fallback.

**Comment by tmikov** [comment] 2023-10-20 02:24
@johnculviner it is not really out of scope. See https://github.com/facebook/hermes/issues/1003 where we asked for a PR. It is just something that we don't feel competent to implement, especially since we won't use it.

**Comment by tmikov** [comment] 2023-10-20 02:29
@psaha-rbi Thanks for posting the v8 and JSC links. I see at least two complications:
1. Where do we get a good 64-bit seed from in a portable way? If not, we would need multiple implementations, at least for Apple, Android, Linux, Windows. Seems like v8 is using a random generator for the seed (why?), but presumably that generator is seeded somewhere. 
2. minstd_rand apparently takes a 32-bit seed.

This does not appear to be a trivial fix.

**Comment by purujit** [comment] 2023-10-20 05:50
> @psaha-rbi Thanks for posting the v8 and JSC links. I see at least two complications:
> 
> 1. Where do we get a good 64-bit seed from in a portable way? If not, we would need multiple implementations, at least for Apple, Android, Linux, Windows. Seems like v8 is using a random generator for the seed (why?), but presumably that generator itself is seeded somewhere.
> 2. minstd_rand apparently takes a 32-bit seed.
> 
> This does not appear to be a trivial fix.

1. You can use a [similar technique as v8](https://github.com/v8/v8/blob/c7a55f9b0b6e65509f62b400f24111b3db0fdbe4/src/base/utils/random-number-generator.cc). On BSD (and Darwin) it uses the ARC4 algorithm to get a 64 bit seed. The ARC4 system itself (I think) tries to get entropy from the kernel and therefore, should be able to give a good random 64 bit seed.
2. It looks like if you use 64 bit LCG (minstd_rand is the 32 bit version of this) you can [use a 64 bit seed] (https://en.cppreference.com/w/cpp/numeric/random/linear_congruential_engine)

**Comment by chakrihacker** [comment] 2023-10-21 05:45
Can I give it a try??

**Comment by tmikov** [comment] 2023-10-21 15:57
@chakrihacker you don't need to ask for permission. Hermes is open source, anyone can submit a PR. We can't "assign tasks" to people 😀

**Comment by woshiccm** [comment] 2023-10-22 07:52
https://github.com/facebook/hermes/pull/1171

**Comment by tmikov** [comment] 2023-10-22 18:50
@psaha-rbi assuming we had a random generator with a 64-bit seed, would constructing it by two calls to std::random_device()() eliminate the problem?

**Comment by tmikov** [comment] 2023-10-22 18:52
@woshiccm thanks for the PR! Can you please explain your solution in detail? How it addresses the problem - is using system time considered good enough? Also, what random generator algorithm are you using? Is it a standard one?

**Comment by purujit** [comment] 2023-10-22 21:28
I'm not a fan of the time based solution from @woshiccm  since it depends on the clock resolution of the system. I think calling random_device() twice to construct a 64 bit seed and using a 64 bit LCG is a better solution like @tmikov proposed. (Responding from my personal account, I'm @psaha-rbi).

**Comment by sebholl** [comment] 2023-10-24 22:42
I put up an alternate PR here: https://github.com/facebook/hermes/pull/1175

**Comment by woshiccm** [comment] 2023-10-28 04:08
> I'm not a fan of the time based solution from @woshiccm since it depends on the clock resolution of the system. I think calling random_device() twice to construct a 64 bit seed and using a 64 bit LCG is a better solution like @tmikov proposed. (Responding from my personal account, I'm @psaha-rbi).

OK, I have refer to v8's code to implement it, could you pls help review again @tmikov @purujit

**Comment by tmikov** [comment] 2023-10-31 04:44
Fixed in https://github.com/facebook/hermes/commit/34f0b2bcd3020e45d5f0b38b230a38324c8ef042

**Closed by tmikov** 2023-10-31 04:44 UTC
Labels: enhancement, community-support-needed
