### ISSUE TITLE
Date constructor accept wrong ISO 8601 date

### ISSUE THREAD

**Issue by clementdejoie** [facebook/hermes#1291] opened 2024-01-31 15:35 UTC
## Bug Description
- [X] I have run `gradle clean` and confirmed this bug does not occur with JSC
- [X] The issue is reproducible with the latest version of React Native.

React Native version: 0.72.4
OS: Android 10

When you define wrong ISO 8601 date like "2024-13-08T00:00:00Z" (there is no 13th month), Hermes engine interpret this value as "Wed Jan 08 2025 01:00:00 GMT+0100"

code example:
`new Date('2024-13-08T00:00:00Z') // Wed Jan 08 2025 01:00:00 GMT+0100`

## The Expected Behavior
With the JSC engine, if you type : `new Date('2024-13-08T00:00:00Z')`, you get `Date { NaN }`.

**Comment by avp** [comment] 2024-01-31 21:51
Thanks for the report, we'll look at the parsing code here.

**Comment by avp** [comment] 2024-01-31 23:08
Looks like a duplicate of https://github.com/facebook/hermes/issues/1148

**Closed by avp** 2024-01-31 23:08 UTC
Labels: bug
