### ISSUE TITLE
Thread 6: "Exception NSException * "Unhandled JS Exception: Error: invalid host, js engine: hermes"

### ISSUE THREAD

**Issue by hacnam0306** [facebook/hermes#1228] opened 2023-12-23 05:46 UTC
<img width="1053" alt="image" src="https://github.com/facebook/hermes/assets/93205714/7f8decaa-c2f5-418f-a473-ab342edd696d">
**Thread 6: "Exception NSException * "Unhandled JS Exception: Error: invalid host, js engine: hermes" when building release schema with react native 0.70.2** 
It's only occur in release mode , when debugging it's run normally

**Comment by tmikov** [comment] 2023-12-23 18:54
Hi, I am sorry you are having this problem, but unfortunately your report doesn't provide enough information to diagnose it, or even to identify that Hermes is the culprit. Unless you can provide a detailed reproduction with the latest version of Hermes, there is not much we can do.

**Comment by karam1ashqar** [comment] 2023-12-24 19:50
same thing happening to me, only in RELEASE, react native app, it happens whenever i try to launch the app, always crashing on launch, 

any update your end ? @hacnam0306 

"Unhandled JS Exception: Error: invalid host, js engine: hermes"

**Comment by hacnam0306** [comment] 2023-12-25 00:47
> same thing happening to me, only in RELEASE, react native app, it happens whenever i try to launch the app, always crashing on launch,
> 
> any update your end ? @hacnam0306
> 
> "Unhandled JS Exception: Error: invalid host, js engine: hermes"

same bro

**Comment by Abramovick** [comment] 2023-12-28 01:56
Also been having the same issue, anyone figured out the solution?

**Comment by tmikov** [comment] 2023-12-28 05:04
Note that this exception is coming from React Native, not Hermes. AFACT, it is thrown from one of these locations:
- https://github.com/facebook/react-native/blob/d992abc56d02a5a0f025d9252b56c3f7c6ce8945/packages/react-native/React/CoreModules/RCTExceptionsManager.mm#L79
- https://github.com/facebook/react-native/blob/d992abc56d02a5a0f025d9252b56c3f7c6ce8945/packages/react-native/React/CxxModule/RCTCxxUtils.mm#L50

I recommend trying with the latest versions of RN and Hermes and asking in React Native.

**Comment by luanlcampos** [comment] 2023-12-29 14:46
Same problem here using RN 0.73.1. Any news on that issue?

**Comment by karam1ashqar** [comment] 2023-12-29 14:47
It was an npm issue for me, I had npm install with --force or legacy peer reps to fix it

**Comment by matheusPcruz18** [comment] 2023-12-29 15:04
> same thing happening to me, only in RELEASE, react native app, it happens whenever i try to launch the app, always crashing on launch,
> 
> any update your end ? @hacnam0306
> 
> "Unhandled JS Exception: Error: invalid host, js engine: hermes"

Same issue here, RN 0.71.14. Only on production IOS.

**Comment by hacnam0306** [comment] 2023-12-29 15:32
hi guys , i fixed it randomly by remove some useless library , checkout the version of reanimated , clean project by delete yarn.lock & node module and reinstall again <3

**Comment by nishadthajudeen001** [comment] 2024-01-03 12:45
Any further update on this?

**Comment by nishadthajudeen001** [comment] 2024-01-04 08:58
Reactotron was causing the issue in release mode, I was able to fix that by commenting out the reactotron code during the release build.

**Comment by liylmn** [comment] 2024-01-04 11:21
> Reactotron was causing the issue in release mode, I was able to fix that by commenting out the reactotron code during the release build.
Could you please elaborate on the same issue，thanks

**Comment by liylmn** [comment] 2024-01-04 11:22
> Reactotron was causing the issue in release mode, I was able to fix that by commenting out the reactotron code during the release build.

Could you please elaborate on the same issue，thanks

**Comment by nishadthajudeen001** [comment] 2024-01-04 14:04
> > Reactotron was causing the issue in release mode, I was able to fix that by commenting out the reactotron code during the release build.
> 
> Could you please elaborate on the same issue，thanks @nishadthajudeen001

Only the Release version APP was crashing with this error for us -"Error: invalid host, js engine: hermes", 

This issue got resolved when we took the release after commenting out the Reactotron code.

**Comment by liylmn** [comment] 2024-01-05 08:58
@nishadthajudeen001 bro, thank you so much. I upgraded my old project to 0.72. x and just deleted these libraries
reactotron-react-native
reactotron-redux
reactotron-redux-saga

**Comment by liylmn** [comment] 2024-01-05 09:45
> > > Reactotron was causing the issue in release mode, I was able to fix that by commenting out the reactotron code during the release build.
> > 
> > 
> > Could you please elaborate on the same issue，thanks @nishadthajudeen001
> 
> Only the Release version APP was crashing with this error for us -"Error: invalid host, js engine: hermes",
> 
> This issue got resolved when we took the release after commenting out the Reactotron code.

bro, thank you so much. Just delete these few libraries
reactotron-react-native
reactotron-redux
reactotron-redux-saga

**Comment by vinesh4Real** [comment] 2024-01-06 01:48
> > > > Reactotron was causing the issue in release mode, I was able to fix that by commenting out the reactotron code during the release build.
> > > 
> > > 
> > > Could you please elaborate on the same issue，thanks @nishadthajudeen001
> > 
> > 
> > Only the Release version APP was crashing with this error for us -"Error: invalid host, js engine: hermes",
> > This issue got resolved when we took the release after commenting out the Reactotron code.
> 
> bro, thank you so much. Just delete these few libraries reactotron-react-native reactotron-redux reactotron-redux-saga

I can confirm. Removing reactotron and reactotron related libraries fixed it.

**Comment by tmikov** [comment] 2024-01-09 18:31
So, this looks like a problem in Reactotron? @Ajmal0197 I see you reported it to Infinite Red, but then closed the issue?

**Comment by Ajmal0197** [comment] 2024-01-09 18:33
> So, this looks like a problem in Reactotron? @Ajmal0197 I see you reported it to Infinite Red, but then closed the issue?

It's temporarily solved will reopen it. Forgot to reopen.

**Comment by vinesh4Real** [comment] 2024-01-09 20:03
@Ajmal0197 @tmikov  I managed to solve it.
Make sure you dont import anything unless you are in development mode.
In our entry file, we were careful to import our reactotron config file (has all the tron config and imports) only if we are in dev mode. Like so,

```
if (__DEV__) {
  import('./ReactotronConfig').then(() =>
    // eslint-disable-next-line no-console
    console.tron.log('Reactotron Configured'),
  );
}
```

But we were also using redux enhancers in our redux store declaration, where the import existed regardless of the environment.  This is where the error was from. I solved it by importing only after confirming dev environment,

```
let getEnhancers = () => {
  if (process.env.NODE_ENV === 'development') {
    const reactotron = require('../../ReactotronConfig').default;
    [reactotron.createEnhancer!()];
  }
  return [];
};

const store = configureStore({
  reducer: rootReducer,
  enhancers: getEnhancers(),
});
```

**Comment by vinesh4Real** [comment] 2024-01-09 20:04
@Ajmal0197 @tmikov  I managed to solve it. Make sure you dont import anything unless you are in development mode.

In our entry file, we were careful to import our reactotron config file (has all the tron config and imports) only if we are in dev mode. Like so,

```
if (__DEV__) {
  import('./ReactotronConfig').then(() =>
    // eslint-disable-next-line no-console
    console.tron.log('Reactotron Configured'),
  );
}
```

But we were also using redux enhancers in our redux store declaration, where the import existed regardless of the environment.  This is where the error was from. I solved it by importing only after confirming dev environment,

```
let getEnhancers = () => {
  if (process.env.NODE_ENV === 'development') {
    const reactotron = require('../../ReactotronConfig').default;
    [reactotron.createEnhancer!()];
  }
  return [];
};

const store = configureStore({
  reducer: rootReducer,
  enhancers: getEnhancers(),
});
```

**Comment by Ajmal0197** [comment] 2024-01-10 05:24
> let getEnhancers = () => {
>   if (process.env.NODE_ENV === 'development') {
>     const reactotron = require('../../ReactotronConfig').default;
>     [reactotron.createEnhancer!()];
>   }
>   return [];
> };

This worked for me thanks:
```
const getEnhancers = (getDefaultEnhancers) => {
  if (process.env.NODE_ENV === 'development') {
    const reactotron = require('../helpers/ReactotronConfig').default;
    return getDefaultEnhancers().concat(reactotron.createEnhancer());
  }
  return getDefaultEnhancers();
};

// https://redux-toolkit.js.org/usage/usage-guide#use-with-redux-persist
const store = configureStore({
  reducer: persistedReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: {
        ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER], //
      },
    }),
  enhancers: getEnhancers,
});
```

**Comment by lachu97** [comment] 2024-01-10 11:48
SIGABRT: Unhandled JS Exception: Error: invalid host, js engine: hermes 
I too getting this same error,that too only in production..I tried it using iphone SE ios version 17+

**Comment by vinesh4Real** [comment] 2024-01-10 13:08
> getEnhancers

Dont you need to call that function?

**Comment by Ajmal0197** [comment] 2024-01-10 13:11
> @Ajmal0197 Dont you need to call that function?

Already calling see last line. Also u can follow this
https://github.com/infinitered/reactotron/issues/1398

**Comment by vinesh4Real** [comment] 2024-01-10 13:14
@Ajmal0197 that's what I mean, you assigned it but its not called. Add open close brackets `getEnhancers()`

**Comment by Ajmal0197** [comment] 2024-01-10 13:15
> @Ajmal0197 that's what I mean, you assigned it but its not called. Add open close brackets `getEnhancers()` 
>Se

We can use like this in es6. It's working i have checked properly in release/debug mode

**Comment by matheusPcruz18** [comment] 2024-01-10 15:13
I just removed all reactotron code from my project and it worked. Thank you guys.

**Comment by nishadthajudeen001** [comment] 2024-01-10 15:19
check this link https://github.com/infinitered/reactotron/issues/1398, latest build 5.0.4 is the culprit for the issue. We will continue to comment out when we take release build still reactotron resolve the issue

**Comment by TrustDec** [comment] 2024-01-17 06:23
Change `reactotron-react-native` in package.json to 5.0.3, instead of ^5.0.3, otherwise the actual version of `reactotron-react-native` in node_modules is 5.0.4

**Comment by sebasgarcia29** [comment] 2024-01-17 16:49
Hello, I remove the dependencies from reactotron-react-native, reactotron-redux, reactotron-redux-saga and reactotron-plugin-zustand works for me, thank you for advices @nishadthajudeen001 !

**Comment by Ajmal0197** [comment] 2024-01-29 03:49
✅ ✅ ✅ 
This is solution for now:
https://github.com/infinitered/reactotron/issues/1398#issuecomment-1913913058

**Comment by SanjayKdotpitch** [comment] 2024-06-03 07:56
Error: Storage for resolved schema shoutem.core.users doesn't exists in state., js engine: hermes 
any solution this error

**Comment by tmikov** [comment] 2024-06-03 20:41
Closing, since after all of this discussion no evidence has emerged pointing to a Hermes problem. (Discussion can continue, the issue isn't locked).

**Closed by tmikov** 2024-06-03 20:41 UTC
Labels: need more info

**Comment by allenben746** [comment] 2024-09-28 22:17
Running into this issue, but I'm not using `reactotron` in my project. Will update this ticket with my findings.

**Comment by yz-xlame** [comment] 2024-10-17 01:47
I am not using `reactotron`, but I am also encountering this issue.
