### ISSUE TITLE
Intl.NumberFormat `notation` not implemented on iOS

### ISSUE THREAD

**Issue by andreialecu** [facebook/hermes#1190] opened 2023-11-16 10:01 UTC
## Problem

See code below:

```ts
let formatter = Intl.NumberFormat('en', { notation: 'compact' });
formatter.format(10000) -> returns 10K on Android, but 10,000 on iOS
```

**Comment by neildhar** [comment] 2023-11-17 16:51
Hey @andreialecu, thanks for reporting this. Closing this as a duplicate of https://github.com/facebook/hermes/issues/1035.

We're definitely aware of the current gaps in our Intl implementation, and are actively investigating ways to close them in the coming months.

**Closed by neildhar** 2023-11-17 16:51 UTC
Labels: enhancement
