### ISSUE TITLE
Hermes iOS not building with use_frameworks!

### ISSUE THREAD

**Issue by bhishakBitcanny** [facebook/hermes#548] opened 2021-07-09 09:51 UTC
## Bug Description

I have created a new project and trying to build it with Hermes enabled. When I try without `use_frameworks!` mentioned in podfile application builds fine. But after mentioning `use_frameworks!` I get the following error mentioned in the attached screenshot. Is there a way to build with `use_frameworks!`?

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version:
React Native version (if any): `0.64.2`
OS version (if any): `11.4 macOS Big Sur`
Xcode version: `12.5.1`

## Steps To Reproduce

1. Create a new RN project
2. Make sure hermes is enabled `:hermes_enabled => true`
3. Add `use_frameworks!` under target
4. Build and face the error

code example:
<img width="1022" alt="Screenshot 2021-07-09 at 3 14 48 PM" src="https://user-images.githubusercontent.com/49839906/125059698-3ceac800-e0c9-11eb-9864-d28baba1bb45.png">

## The Expected Behavior
Successfully build with hermes enabled also with `use_frameworks!`

**Comment by lethienhung** [comment] 2021-07-09 17:30
I've the same issue

**Comment by Huxpro** [comment] 2021-07-09 21:52
Thanks for reporting. This is a known problem. But TBH I'm not sure when would it be fixed. 0.65 doesn't seem to fix it.

cc @Titozzz and @grabbou who may have some more contexts.

**Comment by Titozzz** [comment] 2021-07-09 22:08
From what I know for now:
Hermes is broken with useframeworks on 0.64 and 0.65 ( but the error is not the same ) and Hermes is broken with flipper as indicated inside the podfile when you generate a new project. I personally haven't had time to really use hermes on iOS yet. 

I'm not using useframeworks at all so I'm not sure what is the issue here.

But I think working on compatibility with flipper could be nice. IIRC the issue is with RSocket

**Comment by WVinsmoke1997** [comment] 2021-07-10 02:44
use_frameworks!?

**Comment by bhishakBitcanny** [comment] 2021-07-11 17:47
Thanks, @Titozzz, and @Huxpro for the info.

**Comment by marf** [comment] 2021-09-07 09:26
Hello, any news for a fix ?

We want to use Hermes but also need to keep `use_frameworks!` which is needed for some libraries we use.

Thanks!

**Comment by mjmasn** [comment] 2021-11-08 14:12
Seems to still be an issue in React Native 0.66 (get this error https://github.com/facebook/react-native/issues/32451)

**Comment by romanbarzyczakgelato** [comment] 2022-01-21 11:19
Hi, 
Any updates about it? Is it gonna be fixed?

**Comment by Gu1K** [comment] 2022-03-31 14:16
Hello, Any updates about it?

**Comment by jpporto** [comment] 2022-03-31 15:40
Hi,

Thanks for bringing our attention to this. It turns out this is an RN issue, not a hermes one, so I'll close this bug.

The RN team is currently investigating a fix for this. If you want more updates please open an issue on https://github.com/facebook/react-native.

John Paul

**Closed by jpporto** 2022-03-31 15:40 UTC
Labels: bug
